### ISSUE TITLE
Fix public API breaking changes in 2.7.x

### ISSUE THREAD

**Issue by svettwer** [citrusframework/citrus#549]
We've found some breaking changes in the 2.7.x release family.

This issue contains a list of breaking changes that will be fixed with 2.7.9 to ensure a effortless migration to this version.

All reconstructed methods will be annotated as `@Deprecated` and removed with an upcoming 3.0.0 release.

- [x] #547 - Breaking change in waitFor().http() public API
- [x] #551 - Breaking change in selenium().browser().type() public API
- [x] #552 - MessageContentBuilder interface broken for buildMessageContent
- [x] #553 - Scp client builder does not offer autoReadFiles anymore
- [x] #554 - Change of class signature and typing of WaitConditionBuilder
- [x] #555 - WaitBuilder.condition() changed return type
- [x] #556 - Breaking change in waitFor().message()
- [x] #557 - Breaking change in waitFor().file(String)
- [x] #558 - Breaking change in waitFor().file(File)

**Comment by christophd** [comment]
Honestly, most of the changes listed here are not visible to the end user that just use the Citrus XML or Java DSL. Unless you have custom extensions in your project that deeply customize the behavior of the framework you won't even notice some of these changes. 

What is the motivation behind this? Are there any end users complaining about too many breaking changes in public APIs in previous versions? I can not remember to have received such complains in the past.

I think introducing a deprecated duplication of what has already been changed in order to remove it in the next version (probably soonish v.2.8.0) is not worth the effort.

**Comment by christophd** [comment]
How long are you going to keep the introduced deprecations? Keeping the deprecation for #511 for instance up to v3.0.0 is way too long in my opinion. I suppose to remove most or all of the introduced deprecations with v2.8.0.

**Comment by svettwer** [comment]
Hi! 

>What is the motivation behind this? Are there any end users complaining about too many breaking changes in public APIs in previous versions?

Yes, we recently had complaints by users about such changes.

>I think introducing a deprecated duplication of what has already been changed in order to remove it in the next version (probably soonish v.2.8.0) is not worth the effort.
[...]
How long are you going to keep the introduced deprecations? Keeping the deprecation for #511 for instance up to v3.0.0 is way too long in my opinion.

We're going to remove the deprecated parts of the API with 3.0.0 as we're now following a [semantic versioning](https://semver.org/). In semantic versioning, incompatible API changes are only allowed when upgrading a major version.

BR,
Sven

**Comment by christophd** [comment]
I totally disagree. Those deprecations introduced will bother users for a long time until the next major release then as they have two obviously identical methods to choose from where one of them is deprecated for no obvious reason.

All waitFor deprecations will bother many upcoming users just because somebody is not able to change/adjust a method name or Java DSL dialect improvement when upgrading? You will end up with many more complaints about that for sure.

**Comment by svettwer** [comment]
Hi!

Yes, there will be some deprecated methods available when writing new tests. Nevertheless, existing tests won't break on updates, which is the real benefit in my opinion.

>You will end up with many more complaints about that for sure.

I doubt that this will be the case. But if someone complains, we will explain the reasons.

BR,
Sven

**Comment by svettwer** [comment]
We're not planning to maintain the deprecations as nearly that long. The road map is not finished yet but the next major release isn't that far away as the last was.
