### ISSUE TITLE
Citrus-JDBC improvements

### ISSUE THREAD

**Issue by svettwer** [citrusframework/citrus#600]
Based on the feedback we received last year, we are going to improve the Citrus-JDBC functionality. This includes output parameters in callable statements, JDBC batch statements, various data types and much more.

- [x] https://github.com/citrusframework/citrus/issues/499
- [x] https://github.com/citrusframework/citrus-db/issues/36
- [ ] https://github.com/citrusframework/citrus-db/issues/28
- [ ] https://github.com/citrusframework/citrus-db/issues/29

**Comment by riteshjkeloth** [comment]
Hi,
Do we know if this improvement is already available or when is this expected to be available ?
-Ritesh
